// Secure JavaScript implementation

// XSS prevention with proper sanitization
document.getElementById('searchForm').addEventListener('submit', function(e) {
    e.preventDefault();
    const query = document.getElementById('searchQuery').value;
    
    // Sanitize input before displaying
    const sanitizedQuery = sanitizeHTML(query);
    document.getElementById('results').textContent = 'Results for: ' + sanitizedQuery;
    
    // Simulate an AJAX call
    setTimeout(() => {
        // Create elements properly instead of using innerHTML
        const resultDiv = document.createElement('div');
        const resultText = document.createTextNode('Result found: ');
        const resultSpan = document.createElement('span');
        resultSpan.textContent = sanitizedQuery;
        
        resultDiv.appendChild(resultText);
        resultDiv.appendChild(resultSpan);
        document.getElementById('results').appendChild(resultDiv);
    }, 500);
});

// HTML sanitization function
function sanitizeHTML(str) {
    const temp = document.createElement('div');
    temp.textContent = str;
    return temp.innerHTML;
}

// Secure credential handling
function secureUserAuthentication(username, password) {
    // Instead of storing in localStorage, use a secure authentication mechanism
    // This is just a demonstration - in real apps, use proper auth protocols
    
    // Create a session token instead of storing credentials
    const sessionToken = generateSessionToken();
    
    // Store only the session token, not the credentials
    sessionStorage.setItem('sessionToken', sessionToken);
    
    // Send credentials to server over HTTPS (simulated)
    console.log('Credentials sent securely to server');
}

// Generate a secure session token
function generateSessionToken() {
    // In a real app, this would be generated by the server
    return 'secure-' + Math.random().toString(36).substring(2);
}

// Safe alternative to eval()
function processUserInput(input) {
    // Instead of eval, use safer alternatives based on what you need to do
    // For example, if you need to parse JSON:
    try {
        return JSON.parse(input);
    } catch (e) {
        console.error('Invalid input format');
        return null;
    }
}

// Safe handling of URL parameters
window.onload = function() {
    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.has('welcome')) {
        const welcomeMessage = urlParams.get('welcome');
        // Sanitize and use textContent instead of innerHTML
        document.getElementById('results').textContent = sanitizeHTML(welcomeMessage);
    }
    
    // Add CSRF token to all forms
    addCSRFTokenToForms();
};

// Add CSRF protection to forms
function addCSRFTokenToForms() {
    // In a real app, this token would be generated by the server
    const csrfToken = 'secure-token-' + Date.now();
    
    // Add to all forms
    document.querySelectorAll('form').forEach(form => {
        const tokenInput = document.createElement('input');
        tokenInput.type = 'hidden';
        tokenInput.name = 'csrf_token';
        tokenInput.value = csrfToken;
        form.appendChild(tokenInput);
    });
} 